name: Build Android APK

on:
  push:
    branches: [main, master, flet]
  workflow_dispatch: # Memungkinkan tombol 'Run workflow' manual di GitHub

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK via Flet Action
        id: build
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          build-number: ${{ github.run_number }}
          archive-output: false

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAS4Tool-APK
          path: build/apk/*.apk
          if-no-files-found: error
